import { useEffect, useState } from 'react'

export default function NFLDataPyTesting() {
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')

  useEffect(() => {
    async function load() {
      try {
        const resp = await fetch('/data/nfl_data_py_test.json')
        if (!resp.ok) throw new Error('No test output found. Run scripts/fetch_nfl_data.py or scripts/test.')
        const json = await resp.json()
        setResult(json)
      } catch (err) {
        setError(err.message || 'Failed to load test data.')
      }
    }
    load()
  }, [])

  return (
    <div style={{ maxWidth: '900px', width: '100%', color: '#0f172a', padding: '1rem' }}>
      <h1>nfl_data_py testing</h1>
      <p>
        This page just reads a JSON file generated by running a quick Python snippet using
        <code> nfl_data_py </code>. Use it to confirm the library works locally.
      </p>

      <pre style={{ background: '#f1f5f9', padding: '1rem', borderRadius: '10px', overflowX: 'auto' }}>
{`import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import nfl_data_py as nfl

season = 2023
stats = nfl.import_seasonal_data([season])
weekly = nfl.import_weekly_data([season])
rosters = nfl.import_weekly_rosters([season])

print(len(stats), len(weekly), len(rosters))
print(stats.head(1).to_dict(orient="records")[0])`}
      </pre>

      {error && (
        <p style={{ color: 'crimson', fontWeight: 700 }}>
          {error}
        </p>
      )}

      {result && (
        <pre style={{ background: '#e2e8f0', padding: '1rem', borderRadius: '10px', overflowX: 'auto' }}>
{JSON.stringify(result, null, 2)}
        </pre>
      )}
    </div>
  )
}
